### ISSUE TITLE
Organize Integrations category with subsections

### ISSUE THREAD

**Issue by TC-MO** [apify/apify-docs#1041]
To enhance the organization of our `Integrations` category by creating subsections within the documentation. This will improve navigation and user experience.

Task:
Create sub-categories for integration guides in the documentation and categorize them accordingly. Suggested sub-categories may be but are not limited to:

    Programmatic
    No-code Automation
    Messaging
    Data & AI

Alternatively, use any other categorization scheme that makes sense for our documentation structure.

Details:

    Review the existing integration guides.
    Define and create appropriate sub-categories.
    Reorganize the guides under these new sub-categories.
    Ensure the sidebar reflects the new structure.

Expected Outcome:
A well-organized integration sidebar with clear sub-categories, making it easier for users to find relevant guides.

**Comment by TC-MO** [comment]
Proposed organization scheme:

Programmatic Integrations

-   API
-   Webhooks
-   Actors
-   GitHub
-   Integrate with Apify

No-code/Low-code Automation Platforms

-   Zapier
-   Make
-   Keboola

Messaging and Communication

-   Telegram
-   Slack
-   Gmail
-   Google Drive

Data Integration and Management

-   Airbyte
-   Pinecone

AI and Machine Learning Tools

-   LangChain
-   Flowise
-   LlamaIndex

**Comment by TC-MO** [comment]
Final structure for the Integration sidebar:

Integrations (this page should show a table of the integrations with the same structure as below plus add the ones that don't have page but are listed at https://apify.com/integrations, with all the links including creating new integrations, to make it easy to see all in one place)

Programming

- API
- Webhooks
- GitHub

Actor-to-Actor (instead of just "Actors", this is how it's called on apify.com/integrations)

- Creating integration Actors (instead of "Integration-ready Actors")
- Integrating Actors via API (honestly I have no idea what this page is about, it doesn't provide context)

Workflows & notifications

- Zapier
- Make
- Telegram
- Slack
- Gmail

Data storage

- Airbyte
- Keboola
- Google Drive

AI ecosystem

- LangChain
- LlamaIndex
- Flowise
- Pinecone

Create new (replaces "Integrate with Apify")

**Comment by TC-MO** [comment]
The URL's should not be affected by the changes since they are hardcoded in the front-matter but I will double check it before pushing it to docs.

**Comment by mtrunkat** [comment]
> Integrate with Apify 🤝

I'd keep this separate from any category as it provides instructions for creating any type of external integration of Apify for their service.

**Comment by TC-MO** [comment]
Yes in the final structure, it is kept as a separate document  not bound to any category

**Comment by jancurn** [comment]
Oh right, good point, /integrations/pinecone is fine, no need to add subfolder to the URL

**Comment by TC-MO** [comment]
One suggestion from me, I would assume that Rest API integration guide might be heve the highest traffic and be of most interest to our audience so maybe we could leave it at the top above all others categories. Thoughts?

**Comment by jancurn** [comment]
IMO we don't need to, "API" docs are quite prominent elsewhere
