### ISSUE TITLE
Add Selenium and Java examples to proxy docs

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-docs#106]
We have a request for more frameworks/languages in the proxy docs revamp page:
https://www.notion.so/apify/Proxy-bf9502bee40846b48b42bc0d294752a1

**Comment by m-murasovs** [comment]
For help with code, check
https://apify.com/jancurn/selenium-custom-firefox
https://apify.com/apify/example-selenium/source-code

**Comment by mtrunkat** [comment]
Java requests - long time no see, so closing this.
