### ISSUE TITLE
Error when following Professional scraping tutorial

### ISSUE THREAD

**Issue by tomnosek** [apify/apify-docs#1063]
When following instructions [here](
https://github.com/apify/apify-docs/blob/master/sources/academy/webscraping/web_scraping_for_beginners/crawling/pro_scraping.md#install-crawlee-crawlee-installation), the following error is thrown:
```
(node:38508) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

import { CheerioCrawler } from 'crawlee';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
```
The error is fixed by adding the following attributes to `package.json`:
```
"main": "crawlee.js",
"type": "module",
```
That should likely go after the code example in the "After" paragraph, before the "Then" paragraph.

**Comment by B4nan** [comment]
Hmm, good point, we adopted ESM import syntax in the examples but we haven't really described that you need ESM project for that and how to set it up.

We should add a block like the one in [crawlee docs](https://crawlee.dev/docs/quick-start#crawling).

<img width="983" alt="image" src="https://github.com/apify/apify-docs/assets/615580/4a1c7022-6f1b-409a-b02b-ee79593e424d">
