### ISSUE TITLE
Rename "Output schema" in Apify Docs to "Dataset schema"

### ISSUE THREAD

**Issue by jancurn** [apify/apify-docs#1162]
This was originally referenced in https://github.com/apify/actor-specs/issues/42

For consistency with Actor whitepaper, the page at https://docs.apify.com/platform/actors/development/actor-definition/output-schema should be called "Dataset schema".

Also, please change URL from /output-schema to /dataset-schema, just make sure it's not linked from anywhere, or perhaps we can add redirect for it...

**Comment by jancurn** [comment]
@TC-MO please could you look into this?

**Comment by TC-MO** [comment]
Does this relate only to the title ant `slug` or prose should be changed as well from `output schema` to `dataset schema` ?

**Comment by jancurn** [comment]
Yeah, also the prose. The thing is, "output schema" was always meant to be something bit different, now it's used for the "dataset schema"

**Comment by TC-MO** [comment]
Done with https://github.com/apify/apify-docs/pull/1165

**Comment by jancurn** [comment]
Thank you Michal!
