### ISSUE TITLE
Issues with broken ToC layout

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-docs#1188]
There are a few issues connected to the ToC in the right column on the page.
1. on some pages, it gets displayed under the main article
	- e.g. https://docs.apify.com/platform/actors/development/actor-definition/input-schema/specification/v1
	- it's probably because of some weird interaction between our docs theme, `display: flex` on the main layout and `overflow: auto` on code blocks
	- if you delete long lines in code blocks (e.g. lines 43 and 406 [here](https://github.com/apify/apify-docs/blob/2b1e1eeaeb65ebe493189fb37fbf8dec5d91ed42/sources/platform/actors/development/actor_definition/input_schema/specification.md?plain=1)), the layout gets fixed
2. on some pages, scrolling through the page makes the laout wider / narrower, resulting in the article jumping around
	- it might be connected to long subheadings being marked as current in the ToC

https://github.com/user-attachments/assets/4590a167-a0d7-426b-9648-e3ef87a8948b

Reported here: https://apify.slack.com/archives/C0L33UM7Z/p1725462627933989
cc @barjin

**Comment by barjin** [comment]
The more you know: The HEVC/H.256 codec is proprietary and isn't as widely supported as one might think (read: it doesn't work in Firefox on Linux). _HEVC Advance_ also collects royalties for using the codec. Use [AV1](https://caniuse.com/av1) instead (open, royalty-free, and slightly better supported); be the change! :)

![obrazek](https://github.com/user-attachments/assets/ac9e1a83-9e2d-47b1-8f45-dd93373b2af2)

**Comment by fnesveda** [comment]
Hah, I was actually thinking "which codec should I use? 🤔" when recording this video, but then I thought "it's 2024, H265 has to be supported everywhere by now". Thanks for pointing this out, I didn't think it won't work on Linux.

Anyway, AV1 is not widely supported on iOS devices and Safari on Macs (it only works on iPhone 15 Pro and the latest MacBooks), so I think I'll just stick with H264 for the next few years 😄

I reuploaded the video in H264, does it work for you now?

**Comment by barjin** [comment]
![obrazek](https://github.com/user-attachments/assets/bf4e9347-36ed-4098-951e-c438b782abf3)

Perfect, cheers! (I downloaded the first one and played it in VLC, too, so no hard feelings 😄 ) H264 for the win, I guess :)
