### ISSUE TITLE
Overall issues with docs

### ISSUE THREAD

**Issue by HonzaKirchner** [apify/apify-docs#1284]
- The he most frustrating issue is the inconsistent links between [docs.apify.com/platform](http://docs.apify.com/platform), [console.apify.com](http://console.apify.com/), and the API docs. For example, on the datasets [documentation page](https://docs.apify.com/platform/storage/dataset), there’s a sentence :“To retrieve a list of your datasets, send a GET request to the [Get list of datasets](https://docs.apify.com/api/v2#/reference/datasets/get-list-of-datasets) endpoint.” This link takes you to the top of the API docs rather than the specified resource. Similarly, if you’re in the Console under Actor > API > API endpoints > Run Actor > View API reference, you end up in the middle of the “Resurrect run” endpoint.
- When directed to a specific API doc, such as this [endpoint](https://docs.apify.com/api/v2#tag/DatasetsDataset/operation/dataset_get), it would be really helpful if the left-side menu scrolled to show where I am on the page. Currently, if I want to explore similar endpoints, I have to manually scroll to find my place.
- Some links across the documentation aren’t working. For example, in the [Key-Value Store section](https://docs.apify.com/api/v2#tag/Key-value-storesRecord), the sentence with the “Put record” -  link does not work.
- There are too many small errors in the docs that add up and are hard to tolerate in that extent. For instance, see: https://docs.apify.com/api/v2#tag/ActorsLast-run-object-and-its-storages, or https://docs.apify.com/api/v2#tag/ActorsRun-object

Reported [here](https://apify.slack.com/archives/C010Q0FBYG3/p1731398912774059)

**Comment by B4nan** [comment]
Closing this one as most of the problems were addressed, and we are also working on a new openapi docs which will provide a better UX in general, no plans to spend more time on the current setup outside of content corrections afaik.
