### ISSUE TITLE
Invisible text in darkmode

### ISSUE THREAD

**Issue by gippy** [apify/apify-docs#1296]
In dark mode the "authorization" for users public get API endpoint is invisible, because the section has white background with light text.

You can check the issue here: [user get](https://docs.apify.com/api/v2#tag/UsersPublic-data/operation/user_get)

![image](https://github.com/user-attachments/assets/67ec08c2-15b8-4897-a2b5-1e5238f68e76)
![image](https://github.com/user-attachments/assets/f1b48e3d-cf38-4969-a1b1-e331c248d0eb)

Reported here:
https://apify.slack.com/archives/C0L33UM7Z/p1731924753046469

**Comment by jbartadev** [comment]
Already fixed with the new API reference docs udpates

**Comment by jbartadev** [comment]
The [new API reference docs](https://docs.apify.com/api/v2-new/user-get) don't have this issue and it's not worth it to fix this detail in the old one.
