### ISSUE TITLE
Hard to read headings in Javascript API client section

### ISSUE THREAD

**Issue by nguyeda1** [apify/apify-docs#140]
It is hard to recognize level of individual headings.. the bold font of **Parameters** (see Before picture) takes away attention from **deleteRecord** which is supposed to be a heading for the section

Increasing the font-weight on headings could solve the issue (see After picture).. font-weight: 600 on the pic

## Before
![Screenshot 2020-11-23 at 13.21.51.png](https://images.zenhubusercontent.com/5f97d5fc070d122495a52d6e/a4770b3a-ebfc-4376-83de-02efd8d19408)

## After
![Screenshot 2020-11-23 at 13.28.02.png](https://images.zenhubusercontent.com/5f97d5fc070d122495a52d6e/a3945cc3-150a-486b-aa1e-dd7ab10e8ec3)

**Comment by fnesveda** [comment]
Closing as the API client docs were completely reworked, so this is out of date.
