### ISSUE TITLE
API docs is missing info about /actor-runs API endpoint

### ISSUE THREAD

**Issue by jancurn** [apify/apify-docs#202]
But for example /actor-tasks is documented.

**Comment by m-murasovs** [comment]
@jancurn do you mean that this bit isn't as detailed for `/actor-runs`?

<img width="450" alt="Screenshot 2021-03-03 at 11 04 40" src="https://user-images.githubusercontent.com/38246758/109789087-42626e00-7c10-11eb-9609-a8eceaecf1bb.png">

**Comment by jancurn** [comment]
Oh shit, sorry, I just realized it's [there](https://docs.apify.com/api/v2?utm_source=app#/reference/actor-runs/run-collection), I just didn't find it before. Never mind :)
