### ISSUE TITLE
PHP Examples for docs

### ISSUE THREAD

**Issue by valekjo** [apify/apify-docs#225]
@valekjo commented on [Thu Apr 22 2021](https://github.com/apify/apify-core/issues/2356)

We shoud have examples not only with `curl` buth also with guzzle: https://github.com/guzzle/guzzle.

Slack: https://apifier.slack.com/archives/CGZSN9DQC/p1619076839029300?thread_ts=1619075177.027200&cid=CGZSN9DQC

**Comment by valekjo** [comment]
The examples (generic api call and using proxy) are available in this repository: https://github.com/apify/apify-php-examples

**Comment by m-murasovs** [comment]
done
