### ISSUE TITLE
Mark Live View as deprecated/remove where possible

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-docs#300]
convo https://apifier.slack.com/archives/C01JQ8DLCKS/p1637596986000100

**Comment by mtrunkat** [comment]
Note to this: The container server is still relevant and we need to keep this functionality https://docs.apify.com/actors/running#container-web-server only the live view from SDK that's on the top of this is being removed.

**Comment by m-murasovs** [comment]
Marked Help article: https://app.intercom.com/a/apps/kod1r788/articles/articles/2158740/show
Removed from Tutorials: https://github.com/apify/actor-scraper/pull/151
