### ISSUE TITLE
Make the menu items work with common browser commands

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-docs#306]
Users often open pages in new tabs "for later". Our docs make it super hard for them, because you can't cmd/ctrl click a collapsible link in the menu. You also can't easily copy the link, because the right click menu treats it as a text and not a link.

![image](https://user-images.githubusercontent.com/23726914/143917629-8a120dc5-fc14-4dd1-a39c-1dcf3fd15d41.png)

The non-collapsible menu items can be right clicked, but cannot be ctrl/cmd clicked.

![image](https://user-images.githubusercontent.com/23726914/143917643-f49475ac-f439-4423-b357-cc2a89d3c29b.png)

**Comment by fnesveda** [comment]
This seems to be fixed already.
