### ISSUE TITLE
Improve webhooks docs

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-docs#320]
It appears the docs are out of date and could do with improvement. A couple of people on Discord were confused, as reported by Paulo. Conversation: https://apifier.slack.com/archives/CQ96RHG2U/p1642786975000300

Also check: https://apifier.slack.com/archives/DUC52PG0J/p1647352424354999

Check out Discord to see what they need and check with Platform team how we can improve.

Probably move all the content to one page?

Also see: https://apifier.slack.com/archives/CQ96RHG2U/p1669482412125069

We need to document retries and exponential backoff, this is not described anywhere and users are surprised by this ([Slack](https://apifier.slack.com/archives/C03NSCJ9X47/p1693324765494209)).

**Comment by fnesveda** [comment]
I was reading through the docs now, and I think the issues that people complained about are fixed:
- actions are listed
- variable interpolation is explained
- retries and exponential backoff are there
- the structure is better after Mára's restructuring

I will just close this, if it's needed we can reopen it.
