### ISSUE TITLE
Raise minimum required Node version for Apify SDK in the tutorial docs   

### ISSUE THREAD

**Issue by martinxluptak** [apify/apify-docs#323]
On the following URLs, the articles state that the minimum required Node version to use Apify.js is 10.17. However, upon launching example code snippets in the Getting Started guide, I found out this is not so; the execution crashes because of a missing syntax element.

URLs:
https://sdk.apify.com/docs/guides/getting-started
https://docs.apify.com/storage#apify-sdk
https://help.apify.com/en/articles/1760950-develop-build-and-run-actors-locally-using-the-apify-command-line-client

I ran the following searches to find these URLs (maybe there's more?):
https://docs.apify.com/?q=10.17
https://docs.apify.com/?q=node%20version

Error:
```
<PROJECT_DIR>/node_modules/apify/build/configuration.js:91
        const envKey = Configuration.ENV_MAP_REVERSED[key] ?? key;
                                                            ^

SyntaxError: Unexpected token ?
```

The correct minimum version must be found and this needs to be changed in all places: docs.apify.com , sdk.apify.com , help.apify.com .

**Comment by martinxluptak** [comment]
@B4nan

**Comment by B4nan** [comment]
Good catch, fixed the sdk docs and also changed the suggestion to `fnm` instead of `nvm`. 

Btw we use `engines` in package.json, so you get a warning on installation on older node versions. Rule of thumb, never ignore warnings, it will make your life easier :]

```
npm WARN notsup Unsupported engine for apify@2.2.2: wanted: {"node":">=15.10.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: apify@2.2.2
npm WARN notsup Unsupported engine for got-scraping@3.2.8: wanted: {"node":">=15.10.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: got-scraping@3.2.8
npm WARN notsup Unsupported engine for browser-pool@3.1.0: wanted: {"node":">=15.10.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: browser-pool@3.1.0
npm WARN notsup Unsupported engine for fingerprint-injector@1.0.0: wanted: {"node":">=15.10.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
npm WARN notsup Not compatible with your version of node/npm: fingerprint-injector@1.0.0
```

With yarn it won't even allow you to install it

```
➜  test-engines-check yarn add apify
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error browser-pool@3.1.0: The engine "node" is incompatible with this module. Expected version ">=15.10.0". Got "14.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
