### ISSUE TITLE
Malformed API examples

### ISSUE THREAD

**Issue by valekjo** [apify/apify-docs#398]
Some of the API examples are malformed - due to incorrect apib syntax.

<img width="1558" alt="Snímek obrazovky 2022-06-21 v 10 32 21" src="https://user-images.githubusercontent.com/18436940/174755005-b490748d-0356-4a7a-81ca-5d1b29d9ebb4.png">
<img width="132" alt="Snímek obrazovky 2022-06-21 v 10 32 33" src="https://user-images.githubusercontent.com/18436940/174755034-a82f0bb8-9aa5-422e-b878-229c411025fe.png">

**Comment by mtrunkat** [comment]
@valekjo Please be a bit more concrete in issue descriptions, it took us few minutes to figure out

**Comment by fnesveda** [comment]
This was done with #405.
