### ISSUE TITLE
Browser window doesn't show up as the description of example says

### ISSUE THREAD

**Issue by JJetmar** [apify/apify-docs#417]
After running example from [documentation ](https://developers.apify.com/academy/puppeteer-playwright/browser#launch-options)([code](https://github.com/apify/apify-docs/blob/bf6cec3eacb8644c06207d4176da88e29c676ccf/content/academy/puppeteer_playwright/browser.md?plain=1#L44)):

> ```
> import { chromium } from 'playwright';
> await chromium.launch({ headless: false });
> ```
> 
> Now we'll actually see a browser open up.

This does not actually lead to browser window open up as the upcomming description and image says.

Probably missing call of `newPage()` method, which leads to new browser window open.
```
const browser = await chromium.launch({ headless: false });
await browser.newPage();
```

This is related only to the Playwright example, the Pupetter example works fine.

Could be OS related problem. I tried on Windows 10.

**Comment by mtrunkat** [comment]
This is easier to fix than create an issue :) - https://github.com/apify/apify-docs/pull/539
