### ISSUE TITLE
Update apify.json in CLI doc

### ISSUE THREAD

**Issue by novotnyj** [apify/apify-docs#465]
Update docs with usage of `.actor/actor.json` instead of `apify.json` here: https://docs.apify.com/cli#basic-usage.

**Comment by novotnyj** [comment]
Looking at https://docs.apify.com/cli- it's seems that the content is the CLI readme. I've updated the readme as part of https://github.com/apify/apify-cli/pull/292 so I guess we won't have to do this task...

**Comment by mhamas** [comment]
I checked with Mara this should indeed be the case, so closing this
