### ISSUE TITLE
Add documentation for input UI datepicker and glob editors

### ISSUE THREAD

**Issue by valekjo** [apify/apify-docs#470]

**Comment by gippy** [comment]
Already done:
<img width="871" alt="CleanShot 2023-02-27 at 10 58 39@2x" src="https://user-images.githubusercontent.com/3171028/221532639-270ac198-2a15-4412-b349-b410c6c9932c.png">
<img width="890" alt="CleanShot 2023-02-27 at 10 58 27@2x" src="https://user-images.githubusercontent.com/3171028/221532661-ba2d6e88-01e4-4606-a4ad-135c9327b31b.png">
