### ISSUE TITLE
API reference in new docs is wonky

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-docs#503]
The [API reference](https://docs.apify.com/api/v2) in the new docs is kinda wonky - it takes a long time to load, the black header blinks through, and the scrolling works weird. It's probably because it's in an iframe, but it would still be nice to optimize it somehow.

Reported here: https://apifier.slack.com/archives/C0L33UM7Z/p1675978946175209

https://user-images.githubusercontent.com/2934111/218221281-4b136c1d-a520-4aa5-927c-1187e4c0ffb4.mov

**Comment by mtrunkat** [comment]
The question is if to fix this or wait for the migration to Open API
