### ISSUE TITLE
STRUCTURE: Remove tutorials section from platform docs

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-docs#505]
Redirect the URLs to corresponding articles in the Academy.

<img width="260" alt="obrazek" src="https://user-images.githubusercontent.com/594801/220880880-e57b0f8d-b70e-4539-a8aa-4d831f5dde67.png">

**Comment by mtrunkat** [comment]
@PerVillalva + @mnmkng, do we still want to move some of the tutorials? Or everything worth it is already done?

If we are done, I will find the most similar tutorials and redirect the URLs there after these articles are removed. OK?

**Comment by mnmkng** [comment]
AFAIK Percy moved everything that made sense already. We have this master sheet that tracks it: https://docs.google.com/spreadsheets/d/16WR7UkWn3geu93RtNuBTI1jHGMEM-iBjk2AF-mWAlY0/edit#gid=0

@metalwarrior665 could you please give it a last pass to see if the migration's been done correctly and if it was, we could delete the tutorials from the platform docs.

**Comment by metalwarrior665** [comment]
Will give it a look today/tomorrow
