### ISSUE TITLE
STRUCTURE: Add top level menu to the academy

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-docs#508]
The top-level menu bar will contain:
- Courses
- Tutorials
- Snippets - original Glossary

For **Courses**, we will just display the following in the left menu:

![obrazek](https://user-images.githubusercontent.com/594801/219412097-0fccb564-6299-45d7-8bf4-27356231a728.png)

For **Tutorials** we will have the following in the left menu:

![obrazek](https://user-images.githubusercontent.com/594801/219412212-2485fbe2-e9f1-4ffb-8f03-d33b20a71a54.png)

For **Snippets** we may need to rename the menu links to match the snippet's name. Or @PerVillalva @mnmkng, do you want to keep it as it is?

![obrazek](https://user-images.githubusercontent.com/594801/219412565-7144050b-fec5-4a4b-9116-5f337ee76f0b.png)

**Comment by mnmkng** [comment]
> For Snippets we may need to rename the menu links to match the snippet's name.

I'm not sure I understand. What menu links? Do you mean removing the Tools and Concepts dropdowns and replacing them with labels like the other menus have?

**Comment by mtrunkat** [comment]
So after a discussion with @mnmkng:
- We will keep Glossary called Glossary for now as Snippets could be confusing for developers expecting code snippets
- But we will change the structure with Tools and Concepts being menu categories (non-clickable, always expanded)
