### ISSUE TITLE
Add a landing page at https://docs.apify.com/sdk

### ISSUE THREAD

**Issue by jancurn** [apify/apify-docs#521]
We have these two pages:

- https://docs.apify.com/sdk/js/
- https://docs.apify.com/sdk/python/

But for linking from various sources, it would be convenient also to have a landing page https://docs.apify.com/sdk where you could get to the specific languages.

**Comment by mtrunkat** [comment]
@jancurn I moved this to this repository as v2 will be merged here. Also added to [Notion](https://www.notion.so/apify/Docs-design-improvements-and-additions-fadfae0465974569add2712b26325d6b) for the design team.

**Comment by jancurn** [comment]
thanks @mtrunkat

**Comment by fnesveda** [comment]
I was thinking about the same thing today, perhaps we should have the same thing also for https://docs.apify.com/api/client

**Comment by mtrunkat** [comment]
@fnesveda or perhaps just an API landing page

**Comment by fnesveda** [comment]
https://docs.apify.com/api/ currently redirects to https://docs.apify.com/api/v2, so the API landing page could possibly break some links, but maybe it wouldn't be an issue

**Comment by mtrunkat** [comment]
Console links `/api/v2` so it might be fine

<img width="373" alt="obrazek" src="https://user-images.githubusercontent.com/594801/222466368-7f26c865-b364-4507-8e95-d8fe501e1596.png">
