### ISSUE TITLE
Webhook documentation ref leading to 404

### ISSUE THREAD

**Issue by prokopec-simon** [apify/apify-docs#580]
Hi,
noticed the link for detailed webhook information redirects to a page that doesn't exist (anymore?). Not sure if related to #571. I'd expect the correct redirect is to something like [this](https://docs.apify.com/platform/integrations/webhooks).

It seems to be at multiple places atleast [here](https://github.com/apify/apify-docs/blob/5f11fc4344085a30b8965a656e5e9cc9efa7b86d/sources/platform/api_v2/api_v2_reference.apib#L1)
Example: [here](https://docs.apify.com/api/v2#/reference/actors/run-actor-synchronously-and-get-dataset-items/run-actor-synchronously-with-input-and-get-dataset-items)

**Comment by rabbyn** [comment]
Hi @mtrunkat , can you eventually check that page too, the link to [Actor tasks documentation](https://jsapi.apiary.io/tasks) is broken. Thanks

![image](https://user-images.githubusercontent.com/72968975/235103753-dfae1ded-6594-4eed-9752-e845d9415856.png)
