### ISSUE TITLE
Incorrect version, log on JavaScript SDK 

### ISSUE THREAD

**Issue by HonzaTuron** [apify/apify-docs#626]
<img width="772" alt="image" src="https://github.com/apify/apify-docs/assets/20155254/c00933a8-eb2f-4394-9ad5-713011228e82">
Docs of Apify SDK shows version 3.0, when 3.1.7 is the latest one. It's visible in next version: https://docs.apify.com/sdk/js/reference/next

Also, some content isn't available for 3.0, e.g. log (only in latest)

Log docs doesn't support modern syntax: https://docs.apify.com/sdk/js/reference/next/class/Log

Log doc is duplicated with crawlee one: https://crawlee.dev/api/core/class/Log

Also, console.log is used instead of apify log: https://docs.apify.com/sdk/js/docs/examples/accept-user-input

Reported at: https://apifier.slack.com/archives/C0L33UM7Z/p1687946566788449

**Comment by B4nan** [comment]
I will close this with the v3.1 docs snapshot release, the rest feels irrelevant (or needs to be addressed elsewhere).

> Log docs doesn't support modern syntax: [docs.apify.com/sdk/js/reference/next/class/Log](https://docs.apify.com/sdk/js/reference/next/class/Log)

This needs to be fixed in the jsdoc in apify-shared.

> Log doc is duplicated with crawlee one: [crawlee.dev/api/core/class/Log](https://crawlee.dev/api/core/class/Log)

This is on purpose, as it is exported in both apify sdk and crawlee.

> Also, console.log is used instead of apify log: [docs.apify.com/sdk/js/docs/examples/accept-user-input](https://docs.apify.com/sdk/js/docs/examples/accept-user-input)

I believe we use `console.log` in examples on purpose as its something people already know.

**Comment by B4nan** [comment]
Fixed via https://github.com/apify/apify-sdk-js/commit/5395a297c46aa241889bd91a6077d0d4176b5459
