### ISSUE TITLE
Investigate possible improvements in the search modal

### ISSUE THREAD

**Issue by B4nan** [apify/apify-docs#655]
We recently found out the algolia developer portal has a very nice search experience, they describe how to do it in this article:

https://www.algolia.com/blog/ux/replicating-the-algolia-documentation-search-with-autocomplete/

They use this in the developer docs: https://www.algolia.com/doc/

We'd like to assess how much work would it be to adjust our search to have:
- section tags, the same way as they have it for different languages 
	- e.g. select `js sdk` tag and search only in there
- two-column layout, with the description + ToC, exactly as they do it
	- this will be probably also about how/what we index the content, not just about the UI
- highlighting the matching part in the content, which works on the right side too
	- right now, we have a lot of the matches only for the headings, and those do not contain the `content` property at all, so might be only about improving the index options, the functionality should be already there
	- I'd expect that the match for a heading should also contain some text (the one that the heading is for)

**Comment by barjin** [comment]
2 and 3 are definitely doable (demo [here](https://dashboard.algolia.com/apps/N8EOCSBQGH/explorer/browse/test_test_apify_sdk?query=Secret%20input&refinementList%5Btype%5D%5B%5D=content&searchMode=search)) - index now contains a `toc` field with headings and links to the parts of the article. 

1: tags [seem to](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-tags/) be manually picked - every searchable record can have a `_tags` array, which can be used to filter documents based on the tags there. 

Regarding this, I think the biggest pain will be creating the FE component - we can reuse the Algolia's `autocomplete` library, but that only provides interface for retrieving the records / suggestions, not the FE elements.

**Comment by barjin** [comment]
I'm afraid we'll have to do the custom search box if we want 2 / 3 too. 

Fortunately, Algolia has this thing called [Code Exchange](https://www.algolia.com/developers/code-exchange/frontend-tools/autocomplete-with-preview-panel-in-modal) where they show how you can build stuff with their Autocomplete library. The link leads to a project showing how the preview tab can be built in the search modal.

![obrazek](https://github.com/apify/apify-docs/assets/61918049/d0b46644-2fe0-484e-804b-c5d8b603bda1)

Regarding the estimates, I'd love to say ~1-2 days, as it should be fairly plug-and-play (plus steal the tailwind CSS setup from Algolia, as the demo looks horrendous), but I'm already sure it won't be that easy, ~2-3 full days are a safer estimate.
