### ISSUE TITLE
Add tests to docs repo like the ones in apify-web

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-docs#85]
<img width="1002" alt="Screenshot 2020-08-13 at 09 09 23" src="https://user-images.githubusercontent.com/38246758/90104507-b0167d80-dd44-11ea-8b11-33dbc900ba8d.png">

On every commit, the tests can run to check stuff like description lengths, maybe keyword stuffing (would be cool), if image sizes are decent, if the metadata is right, etc.

Currently tests are in src/build and src/parser, plus a lint test, so we could move them to a Jest file, then run that test file from github/workflows

**Comment by m-murasovs** [comment]
Can we check all the links, too?

**Comment by mtrunkat** [comment]
We could also use markdown linter
