### ISSUE TITLE
Improve writing in Flowise integration page

### ISSUE THREAD

**Issue by janbuchar** [apify/apify-docs#863]
https://docs.apify.com/platform/integrations/flowise

- "If you have any experience with Flowise, you need to download and run it locally." is difficult to understand
- the screenshots have a lot going on in them and it's hard to know what to look for - maybe split them into multiple parts?
- missing "the" before "documentation" in the first tip block

**Comment by TC-MO** [comment]
Fixed with https://github.com/apify/apify-docs/pull/879
