### ISSUE TITLE
Missing image on pagination handling

### ISSUE THREAD

**Issue by HonzaTuron** [apify/apify-docs#899]
https://docs.apify.com/academy/api-scraping/general-api-scraping/handling-pagination#page-number

**Comment by honzajavorek** [comment]
Not sure where is the original one, but if it's lost, perhaps we could use the same image as here? https://docs.apify.com/academy/advanced-web-scraping/scraping-paginated-sites

![image](https://github.com/apify/apify-docs/assets/283441/73809291-6619-4279-9375-ce126dcce14d)
