### ISSUE TITLE
Unclear guidance on what Node.js version to use

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#908]
It is unclear what Node.js version to use when setting up the project. There is no explicit mention in CONTRIBUTING.md. NVM setup suggests v20:

https://github.com/apify/apify-docs/blob/8bd32e16b22dff92bf954048fe03b93707e2c012/.nvmrc#L1

GitHub Actions suggest v18:
https://github.com/apify/apify-docs/blob/8bd32e16b22dff92bf954048fe03b93707e2c012/.github/workflows/test.yaml#L16

**Comment by B4nan** [comment]
both is fine, even node 21 will work. 

sidenote: nvm is slow, use [fnm](https://github.com/Schniz/fnm) instead if you want a node version manager

**Comment by honzajavorek** [comment]
Should the `.nvmrc` file be updated, deleted? GitHub Actions updated? Feels strange it's not synchronized, but YMMV. In my packages I sometimes use

```json
"engines": {
    "node": "20.x"
  },
```

in the `package.json` to denote supported versions. I think `npm install` then gives warning or even error in case I'm installing under unsupported Node.js version.

I discovered [Mise](https://mise.jdx.dev/) some time ago and I use it for everything (Python, JavaScript). So far it's okay :)

**Comment by B4nan** [comment]
its not that important to have this in sync, the project supports multiple node versions. also this is not a library, so its not really important in the first place, all the actual library repos should have this in place.

but yes, we should move the CI to node 20 in general (everywhere). weird that it wasn't updated via renovate automatically.
