### ISSUE TITLE
Is Nginx still needed for local setup?

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#936]
The contributing guide contains the following:

> All the links in the navbar and footer need to be absolute, and they will use a different hostname, configured to docs.apify.loc - to use that, follow the steps below and set up the Nginx server.
> 
> Alternatively, you can skip the Nginx part and navigate to http://localhost:3000/academy or http://localhost:3000/platform manually instead of using links in the navbar.

This seems to be somewhat outdated. When I `npm start` and open http://localhost:3000/ in my browser, the top navigation seems to be working out of the box for both the Academy and Platform.

Links to docs sourced from other repos give me 404s, so I presume if I needed to develop those, I'd still need the Nginx setup. But no manual navigation seems to be needed for the core parts of the docs.

**Comment by B4nan** [comment]
You need nginx if you want to set the whole thing up - if you want to have the complete portal including the child projects like SDKs, as each of those projects will run on a separate port and you need a webserver (nginx) on top of them to have everything on a single domain/port. You won't need this if you only want to deal with the one repository (e.g. this one if you want to update platform/academy docs, or the JS SDK if you want to update some SDK guides).

**Comment by honzajavorek** [comment]
So the sentences could be changed to something along the lines of:

> The parts of the docs sourced from other repositories will give you 404s. If you want to locally run the project with all the other repositories included, clone them all and setup an Nginx server according to the steps below.

I removed mentions of manual navigation, as I don't think it is needed. I have the project running locally and I don't need it. I also removed the initial mention of docs.apify.loc, because I don't see any absolute links to that domain. Does such change of the wording make sense? If so, I can add it to https://github.com/apify/apify-docs/pull/937

**Comment by B4nan** [comment]
> I also removed the initial mention of docs.apify.loc, because I don't see any absolute links to that domain

That's because you don't run it with the `DEV` env var (so [via `npm run start:dev`](https://github.com/apify/apify-docs/blob/master/package.json#L20)). This is still valid for the nginx setup, it will be the domain you will use to access the whole portal (and you need to adjust the `/etc/hosts` file too). 

https://github.com/apify/apify-docs/blob/master/apify-docs-theme/src/config.js#L6

**Comment by honzajavorek** [comment]
Ah, nice. That isn't documented anywhere I believe 😀 I can mention these in the new wording.

**Comment by B4nan** [comment]
Yeah, the guide only showed the original "full" setup, then we changed the defaults so people don't need to deal with nginx just to be able to maintain the content in the current repository, which is 99% of the time.
