### ISSUE TITLE
Ensure we spell Actor with capital A

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#951]
This task is also an opportunity for me to learn more about configuring vale and writing rules for it.

- This is the rule file https://github.com/apify/apify-docs/blob/master/.github/styles/Apify/Capitalization.yml The RE doesn't work correctly now.
- This is the config file https://github.com/apify/apify-docs/blob/master/vale.ini The rule seems to be ON.

The consensus is that Actor should be spelled with capital A. I think I could then go and change it everywhere in the Academy.

**Comment by honzajavorek** [comment]
Completed by https://github.com/apify/apify-docs/pull/1067 and https://github.com/apify/apify-docs/pull/1073 after @jancurn's poke.

**Comment by jancurn** [comment]
Great stuff, thanks guys!
