### ISSUE TITLE
Check broken anchors

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#952]
This is more of a suggestion or an idea for future. We already check whether links are broken. We could check if anchors we point to in our documents actually exist. Those links are valid as in that the page exists and will load in reader's browser, but if the link contains an anchor, the intention was to point to a specific paragraph.

This is something I think Docusaurus could check out of the box (MkDocs has similar features) or that could be achieved by a relatively simple script in our CI, which goes through the resulting HTML and fails if something is off. In the past I wrote a similar script for myself in Python.

**Comment by TC-MO** [comment]
I think this is in Docusaurus v3.1 based on [this](https://docusaurus.io/blog/releases/3.1#broken-anchors-checker) page. Yet another good reason to move forward in the near future to more recent version 😄

**Comment by TC-MO** [comment]
I guess with the update to 3.5.2 this can be closed as we can now use Docusaurus internal link checker to check for broken anchors as well?

**Comment by B4nan** [comment]
i think we need to enable that feature explicitly, @barjin could you please check and possibly enable that?

**Comment by barjin** [comment]
Circling back to this, the linked PR enables the `onBrokenLinks: 'throw'` option, but... well, it uncovers [lots of broken anchors](https://github.com/apify/apify-docs/actions/runs/10767831114/job/29855852050?pr=1190#step:5:112). 

idk whose turf it is now (@TC-MO  / @honzajavorek). Looking at the errors, they seem to be correlated with the new API reference (cc @netmilk) and the explicitly specified heading ids in Markdown (Docusaurus documentation now advises to use the `### Hello World {#my-explicit-id}` syntax ([see docs here](https://docusaurus.io/docs/markdown-features/toc#heading-ids))).

**Comment by honzajavorek** [comment]
Heroes! 🦸 I can help with some portion of it if you want, @TC-MO
