### ISSUE TITLE
Allow continuous delivery of new content

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#954]
As I prepare for adding new content to the Academy, I wonder how to implement the approach of continuous delivery. It could take weeks or months to create a course, and I feel uncomfortable to work on it just locally, then create a huge PR introducing the change. I'd like to create small PRs with incremental additions. For this to properly work, I can think of two strategies:

1. Deploy unfinished content with admonitions warning that the content is a work in progress. I did this in a [guide how to start a Python meetup in your town](https://docs.pyvec.org/guides/meetup.html#propagace). Some chapters are there, some are not, the reader is warned, can give feedback on existing content, or push us to fill in the gaps.
2. Deploy unfinished content as unlisted. The pages are there, but they're not in the navigation. This prevents regular readers to stumble upon something unfinished, but allows me to invite "beta testers" to read the content online.

@TC-MO mentioned that Docusaurus [supports unlisted content](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-pages#unlisted), but we're using an older version, which doesn't have this feature.

What approach do we prefer? Any other ideas?

**Comment by honzajavorek** [comment]
I'll mention @B4nan @mtrunkat by random, as I'm not really sure with who to discuss this.

**Comment by mtrunkat** [comment]
I'd proceed this with [1] as 
- "Open" is our value
- SEO loves listed content
