### ISSUE TITLE
Academy newsletter

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#967]
The [Generating fingerprints](https://docs.apify.com/academy/anti-scraping/mitigation/generating-fingerprints) page contains the following text:

> That's it for the **Mitigation** course for now, but be on the lookout for future lessons! We release lessons as we write them, and will be updating the Academy frequently, so be sure to check back every once in a while for new content! Alternatively, you can subscribe to our mailing list to get periodic updates on the Academy, as well as what Apify is up to.

The words _you can subscribe to our mailing list_ don't link anywhere. Should they? Is there Apify newsletter I should know about? Should I report changes in the Academy to someone from the marketing team? Should the newsletter be marketed like this inside lessons, or should the Docusaurus template take care of it, offering a sign up on every page, somewhere in the footer? Perhaps Academy homepage should have a component for newsletter sign ups?

Alternatively, is it something that never materialized and I should just delete the mention?

**Comment by honzajavorek** [comment]
@mnmkng Do you know about any mailing lists?

**Comment by mnmkng** [comment]
I vaguely remember we had an email form there one day. But we weren't able to regularly create meaningful developer-centric content, so we deleted it.

I would remove the reference.
