### ISSUE TITLE
'Process scraped data with Python' has two titles

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#969]
The page [Process scraped data with Python](https://docs.apify.com/academy/python/process-data-using-python) has two titles rendered, but the source has just one. How to fix this? Summoning @TC-MO for help.

![Screenshot 2024-04-26 at 17-04-59 Process scraped data with Python Academy Apify Documentation](https://github.com/apify/apify-docs/assets/283441/5530f011-882d-4393-a2ad-280080b9ec97)

<img width="955" alt="Screenshot 2024-04-26 at 17 05 27" src="https://github.com/apify/apify-docs/assets/283441/d68d11a3-b74e-46bc-a765-2cfd1bfa6673">

**Comment by TC-MO** [comment]
Seems this is due to the comment being the first thing below front matter, once comment is removed only H1 renders
